// src/components/base/Container.tsx
import Head from "next/head"

export default function Container({
  children,
  wrap,
  summaryLarge,
  title,
  description,
  image,
}: ContainerProps) {
  const wrapContent = wrap ? "wrap-contents" : undefined
  const cardSummary = summaryLarge ? "summary_large_image" : "summary"

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:image" content={image} />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content={cardSummary} />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        <meta name="twitter:image" content={image} />
      </Head>
      <main id={wrapContent}>{children}</main>
    </>
  )
}

// components/Container.vue
<script lang="ts" setup>
const props = defineProps<{
	title: string
	description: string
	class?: string
}>()

useHead({
	title: props.title,
	meta: [
		{ name: "description", content: props.description },
		{ property: "og:title", content: props.title },
		{ property: "og:description", content: props.description },
		{ property: "og:type", content: "website" },
		{ name: "twitter:title", content: props.title },
		{ name: "twitter:description", content: props.description },
		{ name: "twitter:card", content: "summary_large_image" },
	]
})
</script>

<template>
	<main id="page-container" :class="class">
		<slot />
	</main>
</template>
